### ISSUE TITLE
Gasket doesnt reconnect to hostapd.

### ISSUE THREAD

**Issue by Bairdo** [Bairdo/gasket#73]
```
pr 03 21:53:50-617 link023-1ssid DEBUG    waiting for receive
Apr 03 21:53:54-384 link023-2ssid DEBUG    request is "COOKIE=c61f340e380446d0 PING"
Apr 03 21:53:54-622 link023-1ssid DEBUG    request is "COOKIE=7d1a941757f2b2fe PING"
Apr 03 21:53:58-388 link023-2ssid DEBUG    ping timed out.
Apr 03 21:53:58-388 link023-2ssid INFO     Connection to hostapd lost. Retrying to connect
Apr 03 21:53:58-389 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:53:58-627 link023-1ssid DEBUG    ping timed out.
Apr 03 21:53:58-629 link023-1ssid INFO     Connection to hostapd lost. Retrying to connect
Apr 03 21:53:58-630 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:02-395 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:02-395 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:02-636 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:02-637 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:06-401 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:06-402 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:06-642 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:06-643 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:10-408 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:10-649 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:12-411 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:12-652 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:16-417 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:16-418 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:16-658 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:16-658 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:20-424 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:20-424 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:20-664 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:20-665 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:24-428 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:24-671 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:26-431 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:26-674 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:30-436 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:30-437 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:30-679 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:30-680 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:34-443 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:34-463 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:34-686 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:34-687 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:38-469 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:54:38-693 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:54:40-472 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:40-696 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:54:44-478 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
...
Apr 03 21:55:34-579 link023-2ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.6', 8888)
Apr 03 21:55:34-771 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:55:36-582 link023-2ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:55:36-774 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:55:37-85 link023-2ssid ERROR    OSError exception in run. self.stop has not been set.
Apr 03 21:55:37-86 link023-2ssid ERROR    [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_socket_thread.py", line 56, in run
    data = str(self.unsolicited_sock.receive())
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 177, in receive
    return self.soc.recv(size).decode()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_socket_thread.py", line 58, in run
    self.request_sock.ping()
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 147, in ping
    if not self.soc and self.reconnect(self.ifname):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 326, in reconnect
    if not self.open_connection(ifname):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 362, in open_connection
    cookie = self.get_cookie()
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 381, in get_cookie
    return self.request('GET_COOKIE')
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 39, in request
    return self.receive(size=4096)
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 177, in receive
    return self.soc.recv(size).decode()
ConnectionRefusedError: [Errno 111] Connection refused
Apr 03 21:55:40-779 link023-1ssid DEBUG    Couldn't connect (get cookie) to UDP socket ('192.168.11.7', 8888)
Apr 03 21:55:40-780 link023-1ssid DEBUG    request is "GET_COOKIE"
Apr 03 21:55:40-784 link023-1ssid ERROR    OSError exception in run. self.stop has not been set.
Apr 03 21:55:40-786 link023-1ssid ERROR    [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_socket_thread.py", line 56, in run
    data = str(self.unsolicited_sock.receive())
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 177, in receive
    return self.soc.recv(size).decode()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_socket_thread.py", line 58, in run
    self.request_sock.ping()
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 147, in ping
    if not self.soc and self.reconnect(self.ifname):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 326, in reconnect
    if not self.open_connection(ifname):
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 362, in open_connection
    cookie = self.get_cookie()
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 381, in get_cookie
    return self.request('GET_COOKIE')
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 39, in request
    return self.receive(size=4096)
  File "/usr/lib/python3.6/site-packages/gasket/hostapd_ctrl.py", line 177, in receive
    return self.soc.recv(size).decode()
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Bairdo** [comment]
#66
